---
title: "comparison MGM_G CAN"
output: html_document
date: '2022-10-10'
---
# Packages
```{r message=FALSE, warning=FALSE, include=FALSE}
library(stats)
library(rio)
library(tidyverse)
library(dplyr)
library(lavaan)
library(mgm) 
library(qgraph)
library(dplyr)
library(haven)
library(Matrix)
library(igraph)
library(NetworkComparisonTest)
library(plyr)
library(bootnet)
library(openxlsx)
library(matrixcalc)
library(IsingSampler)
library(IsingFit)
library(xtable)
library(ltm)
```


# Import
```{r}
MGM_G <- import("../input/MGM_G.csv")
CAN <- import("../input/CAN.csv")
```

# Objects
```{r}
#mgm
type_mgm <- c(
  "g","g","g","g","g","g","g")

level_mgm <- c(
  1,1,1,1,1,1,1)

shortnames_mgm <- c(
  "Con",
  "LR",
  "comp_",
  "w2r_",
  "in_tr_",
  "reg_",
  "risk_")

longnames_mgm <- c(
  "Support for Conte",
  "L-R self-placement",
  "Compliance to preventive behaviors",
  "Willingness to restrict freedoms",
  "Institutional trust",
  "Support for regional system",
  "Risk perception")

Totalgroup_mgm <- list(
 " "=c(3,4),
 " "=c(1,2,5,6,7))

# define nice colors
colors_mgm <- c("#E8ED61","#8FC45A")

# CAN
shortnames_can <- c(
  "Con",
  "LR",
  "comp_",
  "w2r_",
  "in_tr_",
  "reg_",
  "risk_")

longnames_can <- c(
  "Support for Conte",
  "L-R self-placement",
  "Compliance to preventive behaviors",
  "Willingness to restrict freedoms",
  "Institutional trust",
  "Support for regional system",
  "Risk perception")
```

# Fit models and graphs
```{r}
#mgm
set.seed(1)
FitMGM_G <- mgm(MGM_G, type_mgm, level_mgm, k = 2, binarySign = TRUE)

#enables theme colorblind because we don't need to specify edge.color
inputGraphMGM_G <- FitMGM_G$pairwise$wadj
signsGraphMGM_G <- FitMGM_G$pairwise$signs
signsGraphMGM_G[which(is.na(signsGraphMGM_G))] <- 1
inputGraphMGM_G <- inputGraphMGM_G*signsGraphMGM_G

# refined, no minimum 
GraphMGM_G_nomin<-qgraph(inputGraphMGM_G, 
  layout = "spring", theme = "colorblind", 
  labels = shortnames_mgm,nodeNames = longnames_mgm,
  cut = 0.10, maximum = 1, 
  details = FALSE, vsize=6.0, legend = TRUE, 
  groups=Totalgroup_mgm, color= colors_mgm,
  legend.cex = 0.3, title = "MGM_G no min")

# 0.5
GraphMGM_G_min5<-qgraph(inputGraphMGM_G, 
  layout = "spring", theme = "colorblind", 
  labels = shortnames_mgm,nodeNames = longnames_mgm,
  cut = 0.10, minimum = 0.05, maximum = 1, 
  details = FALSE, vsize=6.0, legend = TRUE, 
  groups=Totalgroup_mgm, color= colors_mgm,
  legend.cex = 0.3, title = "MGM_G min 0.5")

# 0.10
GraphMGM_G_min10<-qgraph(inputGraphMGM_G, 
  layout = "spring", theme = "colorblind", 
  labels = shortnames_mgm,nodeNames = longnames_mgm,
  cut = 0.10, minimum = 0.10, maximum = 1, 
  details = FALSE, vsize=6.0, legend = TRUE, 
  groups=Totalgroup_mgm, color= colors_mgm,
  legend.cex = 0.3, title = "MGM_G min 0.10")

```
```{r}
#CAN
CANFit <- IsingFit(CAN)
inputGraphCAN <- CANFit$weiadj

#no min
GraphCAN_nomin <-qgraph(CANFit$weiadj, layout = 'spring', cut = .10, 
        groups=Totalgroup_mgm, color= colors_mgm, legend = TRUE,
       theme = 'colorblind', labels = shortnames_can,nodeNames = longnames_can,
       legend.cex = 0.4, title = "CAN no minimum")

#0.5
GraphCAN_min5 <-qgraph(CANFit$weiadj, layout = 'spring', cut = .8, 
        groups=Totalgroup_mgm, color= colors_mgm, legend = TRUE,
       theme = 'colorblind', labels = shortnames_can,nodeNames = longnames_can,
       legend.cex = 0.4, cut = 0.10, minimum = 0.05, 
       maximum = 1, title = "CAN minimum 0.5")

#0.10
GraphCAN_min10 <-qgraph(CANFit$weiadj, layout = 'spring', cut = .8, 
        groups=Totalgroup_mgm, color= colors_mgm, legend = TRUE,
       theme = 'colorblind', labels = shortnames_can,nodeNames = longnames_can,
       legend.cex = 0.4, cut = 0.10, minimum = 0.10,
       maximum = 1, title = "CAN minimum 0.10")

```

# Comparison, plots


```{r}
#plot comparison no min
pdf(file= '../Output/comparison/Comparison no min.pdf', paper = "USr", 
    height = 9, width = 12)
L<-averageLayout(GraphCAN_min5,GraphMGM_G_nomin)
lmat <- matrix(1:2, 1, 2)
lo <- layout(lmat, width = c(1, 1.3))
GraphCAN_nomin <-qgraph(CANFit$weiadj, layout = 'spring', cut = .10, 
        groups=Totalgroup_mgm, color= colors_mgm, legend = FALSE,
       theme = 'colorblind', labels = shortnames_can,nodeNames = longnames_can,
       legend.cex = 0.4, title = "CAN")
GraphMGM_G_nomin<-qgraph(inputGraphMGM_G, 
  layout = "spring", theme = "colorblind", 
  labels = shortnames_mgm,nodeNames = longnames_mgm,
  cut = 0.10, maximum = 1, 
  details = FALSE, vsize=6.0, legend = TRUE, 
  groups=Totalgroup_mgm, color= colors_mgm,
  legend.cex = 0.3, title = "mgm")
dev.off()
```
```{r}
#comparison min 0.05
pdf(file= '../Output/comparison/Comparison min 0.05.pdf', paper = "USr", 
    height = 9, width = 12)
L<-averageLayout(GraphCAN_nomin,GraphMGM_G_min5)
lmat <- matrix(1:2, 1, 2)
lo <- layout(lmat, width = c(1, 1.3))
GraphCAN_min5 <-qgraph(CANFit$weiadj, layout = 'spring', cut = .8, 
        groups=Totalgroup_mgm, color= colors_mgm, legend = FALSE,
       theme = 'colorblind', labels = shortnames_can,nodeNames = longnames_can,
       legend.cex = 0.4, cut = 0.10, minimum = 0.05, 
       maximum = 1, title = "CAN minimum 0.5")
GraphMGM_G_min5<-qgraph(inputGraphMGM_G, 
  layout = "spring", theme = "colorblind", 
  labels = shortnames_mgm,nodeNames = longnames_mgm,
  cut = 0.10, minimum = 0.05, maximum = 1, 
  details = FALSE, vsize=6.0, legend = TRUE, 
  groups=Totalgroup_mgm, color= colors_mgm,
  legend.cex = 0.3, title = "MGM_G min 0.5")
dev.off()
```

```{r}
# comparison min 0.10
pdf(file= '../Output/comparison/Comparison min 0.10.pdf', paper = "USr", 
    height = 9, width = 12)
L<-averageLayout(GraphCAN_min10,GraphMGM_G_min10)
lmat <- matrix(1:2, 1, 2)
lo <- layout(lmat, width = c(1, 1.3))
GraphCAN_min10 <-qgraph(CANFit$weiadj, layout = 'spring', cut = .8, 
        groups=Totalgroup_mgm, color= colors_mgm, legend = FALSE,
       theme = 'colorblind', labels = shortnames_can,nodeNames = longnames_can,
       legend.cex = 0.4, cut = 0.10, minimum = 0.10,
       maximum = 1, title = "CAN minimum 0.10")
GraphMGM_G_min10<-qgraph(inputGraphMGM_G, 
  layout = "spring", theme = "colorblind", 
  labels = shortnames_mgm,nodeNames = longnames_mgm,
  cut = 0.10, minimum = 0.10, maximum = 1, 
  details = FALSE, vsize=6.0, legend = TRUE, 
  groups=Totalgroup_mgm, color= colors_mgm,
  legend.cex = 0.3, title = "MGM_G min 0.10")
dev.off()
```
# Centrality 
```{r}
# CAN
CANGraph <- qgraph(CANFit$weiadj, layout = 'spring', cut = .8,
                   labels = longnames_can)
CANCen <- centralityTable(CANGraph, standardized = FALSE)
centralityPlot(CANGraph, scale = 'raw')
```

```{r}
GraphMGMCENT<-qgraph(inputGraphMGM_G, 
  layout = "spring", theme = "colorblind",
  labels = longnames_mgm, minimum = 0,
  cut = 0.10, maximum = 1, details = TRUE,
  legend = FALSE, title = "Centrality table")
#centrality Total
centMGM <- centralityTable(GraphMGMCENT,standardized = FALSE)
centralityPlot(GraphMGMCENT, include = c("Strength"),scale = "raw",
               orderBy = "Strength")

```

```{r}
#comparison
pdf(file= '../Output/comparison/Comparison Centrality Table.pdf')
centralityPlot(list(CAN=CANGraph,mgm=GraphMGMCENT), include = c("Strength"),
               scale = "z-scores", orderBy = "Strength")
dev.off()

```
# NCT
```{r}
#Network comparison test

set.seed(1)
names(MGM_G) <- names(CAN)
# i reduce iteration from 1k to 100
NCT_comparison <- NCT(CAN, MGM_G, it = 100, test.edges = TRUE, edges = "all")
# Difference in global strength p-value:
NCT_comparison$glstrinv.real
NCT_comparison$glstrinv.pval #no diff!
# Maximum difference in edge weights:
NCT_comparison$nwinv.real
NCT_comparison$nwinv.pval #no diffm also for edges!
# Which edges significantly differ?
NCT_comparison$einv.pvals[which(NCT_comparison$einv.pvals[,3] < 0.05), ]
```

```{r}
#input for NCTgraph
inputNCTgraph <- inputGraphCAN - inputGraphMGM_G
#the line below sets the not-significant edge weight differences 
#in the upper triangle of the input matrix to 0
inputNCTgraph[upper.tri(inputNCTgraph)][which(NCT_comparison$einv.pvals$`p-value` >= .05)] <- 0 
#this sets the lower triangle of the matrix to be symmetric 
#with the upper triangle
inputNCTgraph <- forceSymmetric(inputNCTgraph)

#graph
pdf('../Output/comparison/NCT.pdf',paper = "USr", height = 9, width = 12)
qgraph(inputNCTgraph, layout = GraphCAN_nomin$layout, theme = "colorblind",
       labels = shortnames_can, nodeNames = longnames_can,vsize=6.0,
       title = "NCT", edge.labels=FALSE, legend = TRUE, legend.cex = 0.4)
dev.off()
```


```{r}
#DA FARE
DiffCANmgm<- inputGraphCAN - inputGraphMGM_G
NCTExcel <- inputGraphCAN - inputGraphMGM_G
#line below sets the not-significant edge weight differences 
#in the upper triangle of the input matrix to 0
NCTExcel[upper.tri(NCTExcel)][which(NCT_comparison$einv.pvals$`p-value` >= .05)] <- 0
NCTExcel<-upper.triangle(NCTExcel)
NCTExcel[NCTExcel == 0] <- NA
ExcelNCTTotal<- list("CAN" = inputGraphCAN, "mgm" = inputGraphMGM_G, 
                     "diff" = DiffCANmgm, "NCT" = NCTExcel)
write.xlsx(ExcelNCTTotal,"../Output/comparison/NCT edge difference.xlsx", 
           colWidths = "auto", rowNames = TRUE)
```


# Edge weights to Excel
```{r}
##only upper triangle without edge weigths 0 for readability

EdgeWeight_CAN_half<-upper.triangle(inputGraphCAN)
EdgeWeight_MGM_half<-upper.triangle(inputGraphMGM_G)


EdgeWeight_CAN_half[EdgeWeight_CAN_half == 0] <- NA
EdgeWeight_MGM_half[EdgeWeight_MGM_half == 0] <- NA

EdgeWeightsExcel_half<- list("CAN" = EdgeWeight_CAN_half,
                             "MGM" = EdgeWeight_MGM_half)
write.xlsx(EdgeWeightsExcel_half, 
           "../Output/comparison/EdgeWeightsExcel can vs mgm.xlsx", 
           colWidths = "auto", rowNames = TRUE)

```

